{
 "title": "Cluster Linking",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_server_cluster_link_metrics_link_fetcher_count, statefulset_kubernetes_io_pod_name)"
    }
   },
   { "name": "percentile", "label": "Percentile", "query": { "query": "label_values(quantile)" } },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka_log_log_value,topic)"
    }
   },
   {
    "name": "link",
    "label": "link",
    "query": {
     "query": "label_values(kafka_server_cluster_link_metrics_link_fetcher_count,link_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "auto_mirror_created_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metrics_auto_mirror_created_total{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "auto_mirror_create_failed_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metrics_auto_mirror_create_failed_total{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "prefixed_auto_mirror_created_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metrics_prefixed_auto_mirror_created_total{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "prefixed_auto_mirror_create_failed_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metrics_prefixed_auto_mirror_create_failed_total{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "unavailable_link_count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metrics_unavailable_link_count{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "mirror_topic_lag",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metrics_mirror_topic_lag{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\", topic=~\"$topic\"}",
     "legendFormat": "{{topic}}-{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  { "title": "Cluster Link Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Connection Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metadata_metrics_connection_count{statefulset_kubernetes_io_pod_name=~\"$instance\", link_name=~\"$link\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Connection Creation Total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metadata_metrics_connection_creation_total{statefulset_kubernetes_io_pod_name=~\"$instance\", link_name=~\"$link\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "request_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metadata_metrics_request_total{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "request_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 41 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metadata_metrics_request_rate{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "network_io_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metadata_metrics_network_io_total{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "network_io_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 49 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metadata_metrics_network_io_rate{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Select Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metadata_metrics_select_total{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Select Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 56 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metadata_metrics_select_rate{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "incoming_byte_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metadata_metrics_incoming_byte_total{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Incoming byte rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 62 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metadata_metrics_incoming_byte_rate{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Outgoing byte total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metadata_metrics_outgoing_byte_total{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Outgoing byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 68 },
   "targets": [
    {
     "expr": "kafka_server_cluster_link_metadata_metrics_outgoing_byte_rate{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
     "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Cluster Link Fetcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Max Lag",
     "type": "timeseries",
     "description": "Maximum lag in messages between the replicas on the destination cluster and the leader replica on the source cluster. Provides an indication of overall cluster link health and a relative measure of whether the destination cluster is lagging behind.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "kafka_server_link_clusterlinkfetchermanager_value{name=\"MaxLag\", link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
       "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
      }
     ]
    },
    {
     "title": "Total Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "targets": [
      {
       "expr": "kafka_server_link_clusterlinkfetchermanager_value{name=\"TotalLag\", link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
       "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
      }
     ]
    },
    {
     "title": "Mirror Topic Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "kafka_server_cluster_link_metrics_mirror_topic_lag",
       "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
      }
     ]
    },
    {
     "title": "Dead Thread Count",
     "type": "timeseries",
     "description": "Number of dead threads of type ClusterLinkThread, where a dead thread is indicative of an issue with fetching from the source cluster for a partition.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "targets": [
      {
       "expr": "kafka_server_link_clusterlinkfetchermanager_value{name=\"DeadThreadCount\", link_name=~\"$link\",statefulset_kubernetes_io_pod_name=~\"$instance\"}",
       "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
      }
     ]
    },
    {
     "title": "Total Fetch Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "kafka_server_link_clusterlinkfetchermanager_value{name=\"TotalFetchRate\", link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
       "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
      }
     ]
    },
    {
     "title": "Failed Partitions Count",
     "type": "timeseries",
     "description": "Number of failed mirror partitions for which the broker is leader. A partition may be in a failed state if the source partition’s epoch has gone backwards; for example, if the topic was recreated.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "kafka_server_link_clusterlinkfetchermanager_value{name=\"FailedPartitionsCount\", link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
       "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replica Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Throttled Link Replica Per Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "kafka_server_replicamanager_count{name=\"ThrottledClusterLinkReplicasPerSec\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
       "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Metrics ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Delayed operations ",
     "type": "stat",
     "description": "Provides metrics on delayed operations on the cluster link.",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_delayedoperationpurgatory_value{name=\"NumDelayedOperations\", delayedOperation=\"ClusterLink\"})",
       "legendFormat": "DelayedOperations"
      }
     ]
    },
    {
     "title": "Total Time Ms",
     "type": "timeseries",
     "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
     "gridPos": { "h": 6, "w": 7, "x": 4, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_count{name=\"TotalTimeMs\", request=\"CreateClusterLinks\"}[5m]))",
       "legendFormat": "CreateClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_totaltimems{request=\"DeleteClusterLinks\"}[5m]))",
       "legendFormat": "DeleteClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_totaltimems{request=\"ListClusterLinks\"}[5m]))",
       "legendFormat": "ListClusterLinks"
      }
     ]
    },
    {
     "title": "Request Bytes",
     "type": "timeseries",
     "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
     "gridPos": { "h": 6, "w": 10, "x": 11, "y": 84 },
     "targets": [
      {
       "expr": "sum(kafka_network_requestmetrics_count{name=\"RequestBytes\", request=\"CreateClusterLinks\"})",
       "legendFormat": "CreateClusterLinks"
      },
      {
       "expr": "sum(kafka_network_requestmetrics_count{name=\"RequestBytes\", request=\"DeleteClusterLinks\"})",
       "legendFormat": "DeleteClusterLinks"
      },
      {
       "expr": "sum(kafka_network_requestmetrics_count{name=\"RequestBytes\", request=\"ListClusterLinks\"})",
       "legendFormat": "ListClusterLinks"
      }
     ]
    },
    {
     "title": "Response Queue Time Ms",
     "type": "timeseries",
     "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_count{name=\"ResponseQueueTimeMs\", request=\"CreateClusterLinks\"}[5m]))",
       "legendFormat": "CreateClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_responsequeuetimems{request=\"DeleteClusterLinks\"}[5m]))",
       "legendFormat": "DeleteClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_responsequeuetimems{request=\"ListClusterLinks\"}[5m]))",
       "legendFormat": "ListClusterLinks"
      }
     ]
    },
    {
     "title": "Local Time Ms",
     "type": "timeseries",
     "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_count{name=\"LocalTimeMs\", request=\"CreateClusterLinks\"}[5m]))",
       "legendFormat": "CreateClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_localtimems{request=\"DeleteClusterLinks\"}[5m]))",
       "legendFormat": "DeleteClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_localtimems{request=\"ListClusterLinks\"}[5m]))",
       "legendFormat": "ListClusterLinks"
      }
     ]
    },
    {
     "title": "Request Queue Time Ms",
     "type": "timeseries",
     "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_count{name=\"RequestQueueTimeMs\", request=\"CreateClusterLinks\"}[5m]))",
       "legendFormat": "CreateClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_requestqueuetimems{request=\"DeleteClusterLinks\"}[5m]))",
       "legendFormat": "DeleteClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_requestqueuetimems{request=\"ListClusterLinks\"}[5m]))",
       "legendFormat": "ListClusterLinks"
      }
     ]
    },
    {
     "title": "Throttle Time Ms",
     "type": "timeseries",
     "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_count{name=\"ThrottleTimeMs\", request=\"CreateClusterLinks\"}[5m]))",
       "legendFormat": "CreateClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_throttletimems{request=\"DeleteClusterLinks\"}[5m]))",
       "legendFormat": "DeleteClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_throttletimems{request=\"ListClusterLinks\"}[5m]))",
       "legendFormat": "ListClusterLinks"
      }
     ]
    },
    {
     "title": "Remote Time Ms",
     "type": "timeseries",
     "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_count{name=\"RemoteTimeMs\", request=\"CreateClusterLinks\"}[5m]))",
       "legendFormat": "CreateClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_remotetimems{request=\"DeleteClusterLinks\"}[5m]))",
       "legendFormat": "DeleteClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_remotetimems{request=\"ListClusterLinks\"}[5m]))",
       "legendFormat": "ListClusterLinks"
      }
     ]
    },
    {
     "title": "Response Send Time Ms",
     "type": "timeseries",
     "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_count{name=\"ResponseSendTimeMs\", request=\"CreateClusterLinks\"}[5m]))",
       "legendFormat": "CreateClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_responsesendtimems{request=\"DeleteClusterLinks\"}[5m]))",
       "legendFormat": "DeleteClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_responsesendtimems{request=\"ListClusterLinks\"}[5m]))",
       "legendFormat": "ListClusterLinks"
      }
     ]
    },
    {
     "title": "Response Send IO Time Ms",
     "type": "timeseries",
     "description": "Depending on the request name, provides statistics on requests on the cluster link, including requests and response times, time requests wait in the queue, size of requests (bytes), and so forth.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_count{name=\"ResponseSendIoTimeMs\", request=\"CreateClusterLinks\"}[5m]))",
       "legendFormat": "CreateClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_responsesendiotimems{request=\"DeleteClusterLinks\"}[5m]))",
       "legendFormat": "DeleteClusterLinks"
      },
      {
       "expr": "sum(rate(kafka_network_requestmetrics_responsesendiotimems{request=\"ListClusterLinks\"}[5m]))",
       "legendFormat": "ListClusterLinks"
      }
     ]
    }
   ]
  },
  {
   "title": "Destination Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Mirrored Partitions Blocked",
     "type": "gauge",
     "description": "Number of mirrored partitions that are blocked on fetching data due to issues on the source cluster.",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_value{name=\"BlockedOnMirrorSourcePartitionCount\"})",
       "legendFormat": " {{instance}}"
      }
     ]
    },
    {
     "title": "Mirrored Topic under replicated.",
     "type": "gauge",
     "description": "Number of mirrored partitions that are under replicated.",
     "gridPos": { "h": 5, "w": 4, "x": 5, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_value{name=\"UnderReplicatedMirrorPartitions\"})"
      }
     ]
    },
    {
     "title": "Consumer offsets committed rate",
     "type": "timeseries",
     "description": "Rate per second and total number of consumer offsets committed for a cluster link.\n\nHelps verify if offset migration is happening correctly, a critical metric for failover readiness scenarios.",
     "gridPos": { "h": 10, "w": 9, "x": 9, "y": 85 },
     "targets": [
      {
       "expr": "kafka_server_cluster_link_metrics_consumer_offset_committed_rate{link_name=~\"$link\", statefulset_kubernetes_io_pod_name=~\"$instance\"}",
       "legendFormat": "{{link_name}}-{{statefulset_kubernetes_io_pod_name}}"
      }
     ]
    },
    {
     "title": "Mirrored Topic under min isr.",
     "type": "gauge",
     "description": "Number of mirrored partitions that are under min ISR.",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 90 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_value{name=\"UnderMinIsrMirrorPartitionCount\"})"
      }
     ]
    },
    {
     "title": "Mirror Partition Count",
     "type": "gauge",
     "description": "Number of actively mirrored partitions for which the broker is leader",
     "gridPos": { "h": 5, "w": 4, "x": 5, "y": 90 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_cluster_link_metrics_mirror_partition_count{link_name=~\"$link\"})",
       "legendFormat": "{{link_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Source Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "request-byte-total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
     "targets": [
      {
       "expr": "kafka_server_cluster_link_source_metrics_fetch_request_byte_total{statefulset_kubernetes_io_pod_name=~\"$instance\"}",
       "legendFormat": "{{link_id}}"
      }
     ]
    },
    {
     "title": "request-total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
     "targets": [
      {
       "expr": "kafka_server_cluster_link_source_metrics_fetch_request_total{env=~\"$env\",instance=~\"$instance\"}",
       "legendFormat": "{{link_id}}"
      }
     ]
    },
    {
     "title": "response-byte-total",
     "type": "timeseries",
     "description": "\n\nHelps verify if offset migration is happening correctly, a critical metric for failover readiness scenarios.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
     "targets": [
      {
       "expr": "kafka_server_cluster_link_source_metrics_fetch_response_byte_total{env=~\"$env\",instance=~\"$instance\"}",
       "legendFormat": "{{link_id}}"
      }
     ]
    },
    {
     "title": "response-time-ns-avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
     "targets": [
      {
       "expr": "kafka_server_cluster_link_source_metrics_fetch_response_time_ns_avg{env=~\"$env\",instance=~\"$instance\"}",
       "legendFormat": "{{link_id}}"
      }
     ]
    }
   ]
  }
 ]
}