## Configure grafana datasources
## ref: http://docs.grafana.org/administration/provisioning/#datasources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        access: proxy
        isDefault: true
## Configure grafana dashboard providers
## ref: http://docs.grafana.org/administration/provisioning/#dashboards
##
## `path` must be /var/lib/grafana/dashboards/<provider_name>
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers: 
    - name: 'clusterlinking'
      orgId: 1
      folder: 'clusterlinking'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/clusterlinking   
dashboardsConfigMaps: 
  clusterlinking: "clusterlinking-dashboard"
  
   

 